ren "White fog.webp" "White-fog.webp"
ren "Snowstorm.webp" "Snowstorm.webp"
ren "Gale.webp" "Gale.webp"
ren "Heavy snow.webp" "Heavy-snow.webp"
ren "Heavy rain.webp" "Heavy-rain.webp"
ren "Red fog.webp" "Red-fog.webp"
ren "Blue fog.webp" "Blue-fog.webp"
ren "Green fog.webp" "Green-fog.webp"
ren "Magic rise.webp" "Magic-rise.webp"
ren "Sunshine.webp" "Sunshine.webp"
ren "Sand storm.webp" "Sand-storm.webp"
ren "Breeze.webp" "Breeze.webp"
ren "Light snow.webp" "Light-snow.webp"
ren "Light rain.webp" "Light-rain.webp"
ren "Moonshine.webp" "Moonshine.webp"
